# ==============================================================================
# 04_make_main_figures.R
# Figure 1: wEVSI, common population-level decision.
# Figure 2: wEVSI, subgroup-specific decisions.
# Figure 3: 9-panel wENBS, common population-level decision.
# Figure 4: 9-panel wENBS, subgroup-specific decisions.
#
# The 9-panel figures use recruitment-cost rows ($0, $3,000, $6,000),
# borrowing-model columns, and filled points to mark exact numerical maxima.
# Base R graphics are used so no contributed plotting package is required.
# ==============================================================================

script_directory <- function() {
  arguments <- commandArgs(trailingOnly = FALSE)
  file_argument <- grep("^--file=", arguments, value = TRUE)

  if (length(file_argument) == 1L) {
    # Rscript encodes spaces in --file= as "~+~"; decode before resolving.
    dirname(normalizePath(
      gsub("~+~", " ", sub("^--file=", "", file_argument), fixed = TRUE)
    ))
  } else {
    getwd()
  }
}

ROOT <- script_directory()
source(file.path(ROOT, "00_analysis_parameters.R"), local = TRUE)

ANALYSIS_SIGNATURE <- compute_analysis_signature(ROOT)
RESULT_DIR <- file.path(ROOT, OUTPUT$main_results_directory)
FIGURE_DIR <- file.path(ROOT, OUTPUT$main_figures_directory)
dir.create(FIGURE_DIR, recursive = TRUE, showWarnings = FALSE)

wevsi_path <- file.path(RESULT_DIR, "main_wevsi_summary.csv")
wenbs_path <- file.path(RESULT_DIR, "main_wenbs_summary.csv")
optimal_path <- file.path(RESULT_DIR, "optimal_allocation_summary.csv")
required_paths <- c(wevsi_path, wenbs_path, optimal_path)
missing_paths <- required_paths[!file.exists(required_paths)]

if (length(missing_paths) > 0L) {
  stop(
    "Missing main-analysis result files: ",
    paste(missing_paths, collapse = ", "),
    ". Run 03_run_main_analysis.R first.",
    call. = FALSE
  )
}

wevsi <- utils::read.csv(
  wevsi_path,
  stringsAsFactors = FALSE,
  check.names = FALSE
)
wenbs <- utils::read.csv(
  wenbs_path,
  stringsAsFactors = FALSE,
  check.names = FALSE
)
optimal <- utils::read.csv(
  optimal_path,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

validate_signature <- function(data, label) {
  if (!("analysis_signature" %in% names(data))) {
    stop(label, " lacks analysis_signature.", call. = FALSE)
  }

  signatures <- unique(as.character(data$analysis_signature))
  signatures <- signatures[!is.na(signatures) & nzchar(signatures)]

  if (length(signatures) != 1L || signatures[1] != ANALYSIS_SIGNATURE) {
    stop(
      label,
      " was not generated by the current code. Run 07_run_all.R.",
      call. = FALSE
    )
  }
}

validate_signature(wevsi, "main_wevsi_summary.csv")
validate_signature(wenbs, "main_wenbs_summary.csv")
validate_signature(optimal, "optimal_allocation_summary.csv")

expected_costs <- as.numeric(TRIAL$recruitment_cost_increment_A_usd)
observed_costs <- sort(unique(as.numeric(wenbs$cost_increment_A_usd)))
if (length(observed_costs) != length(expected_costs) ||
    any(abs(observed_costs - sort(expected_costs)) > 1e-12)) {
  stop("Main wENBS results do not contain exactly $0, $3,000, and $6,000.", call. = FALSE)
}

weight_labels <- format(RAW_EQUITY_WEIGHT_A, trim = TRUE, scientific = FALSE)
weight_colors <- PLOT$colors[seq_along(RAW_EQUITY_WEIGHT_A)]
names(weight_colors) <- weight_labels

percent_axis <- function(values) {
  paste0(round(100 * values), "%")
}

# Pad the allocation axis slightly so a maximum marker sitting on the first or
# last grid point is drawn whole rather than sliced by the panel border.
allocation_x_limits <- function() {
  range(ALLOCATION_GRID) + c(-1, 1) * 0.6 * SIMULATION$allocation_step
}

pretty_qaly_breaks <- function(y_limits, n = 5L) {
  pretty(y_limits, n = n)
}

open_graphics_device <- function(path, width, height, type) {
  if (type == "png") {
    grDevices::png(
      filename = path,
      width = width,
      height = height,
      units = "in",
      res = PLOT$png_dpi,
      pointsize = PLOT$base_pointsize
    )
  } else if (type == "pdf") {
    grDevices::pdf(
      file = path,
      width = width,
      height = height,
      useDingbats = FALSE,
      pointsize = PLOT$base_pointsize
    )
  } else {
    stop("Unknown graphics type: ", type, call. = FALSE)
  }
}

with_graphics_device <- function(path, width, height, type, plotting_function) {
  open_graphics_device(path, width, height, type)
  on.exit(grDevices::dev.off(), add = TRUE)
  plotting_function()
  invisible(path)
}

# Draw the equity-weight legend in a reserved strip below every panel, so it
# can never overlap a curve. Call this last: it overlays a full-device plotting
# region on top of the finished panels.
draw_outer_legend <- function(show_maximum_points) {
  graphics::par(
    fig = c(0, 1, 0, 1),
    oma = c(0, 0, 0, 0),
    mar = c(0, 0, 0, 0),
    new = TRUE
  )
  graphics::plot(
    0, 0,
    type = "n",
    axes = FALSE,
    xlab = "",
    ylab = "",
    xlim = c(0, 1),
    ylim = c(0, 1)
  )
  graphics::legend(
    x = 0.5,
    y = 0,
    xjust = 0.5,
    yjust = 0,
    legend = weight_labels,
    col = weight_colors,
    lty = PLOT$line_types,
    lwd = PLOT$line_width,
    pch = if (show_maximum_points) {
      rep(PLOT$maximum_point_character, length(weight_labels))
    } else {
      NA
    },
    pt.cex = rep(PLOT$maximum_point_size, length(weight_labels)),
    title = PLOT_LABELS$equity_legend,
    horiz = TRUE,
    bty = "n",
    cex = PLOT$legend_cex
  )
}

plot_wevsi_figure <- function(decision_structure, output_stem) {
  plot_data <- wevsi[
    wevsi$decision_structure == decision_structure,
    ,
    drop = FALSE
  ]

  if (nrow(plot_data) == 0L) {
    stop("No wEVSI rows for decision structure: ", decision_structure, call. = FALSE)
  }

  y_limits <- range(c(0, plot_data$wEVSI), finite = TRUE)
  y_padding <- max(diff(y_limits) * 0.05, 1e-4)
  y_limits <- y_limits + c(-y_padding, y_padding)
  y_breaks <- pretty_qaly_breaks(y_limits)

  draw <- function() {
    old_par <- graphics::par(no.readonly = TRUE)
    on.exit(graphics::par(old_par), add = TRUE)

    graphics::par(
      mfrow = c(1, nrow(BORROWING)),
      mar = c(2.6, 4.2, 3.0, 0.9),
      oma = c(6.6, 2.4, 0.6, 0.6),
      xaxs = "i",
      yaxs = "i"
    )
    # Undo the automatic 0.66 text reduction applied to multi-column layouts.
    graphics::par(cex = 1)

    for (borrowing_index in seq_len(nrow(BORROWING))) {
      borrowing_id <- BORROWING$borrowing_id[borrowing_index]
      panel_data <- plot_data[
        plot_data$borrowing_id == borrowing_id,
        ,
        drop = FALSE
      ]

      graphics::plot(
        NA_real_,
        NA_real_,
        xlim = allocation_x_limits(),
        ylim = y_limits,
        xlab = "",
        ylab = "",
        axes = FALSE,
        main = BORROWING$borrowing_facet_label[borrowing_index],
        cex.main = PLOT$panel_title_cex
      )
      graphics::abline(
        h = 0,
        lty = PLOT$zero_line_type,
        col = "grey55"
      )
      graphics::abline(
        v = unname(CASE_STUDY$population_share["A"]),
        lty = PLOT$population_share_line_type,
        col = "grey35"
      )

      for (weight_index in seq_along(RAW_EQUITY_WEIGHT_A)) {
        weight_value <- RAW_EQUITY_WEIGHT_A[weight_index]
        curve <- panel_data[
          panel_data$raw_weight_A == weight_value,
          ,
          drop = FALSE
        ]
        curve <- curve[order(curve$p_A), , drop = FALSE]

        if (nrow(curve) != length(ALLOCATION_GRID)) {
          stop("Incomplete main wEVSI figure panel.", call. = FALSE)
        }

        graphics::lines(
          curve$p_A,
          curve$wEVSI,
          col = weight_colors[weight_index],
          lty = PLOT$line_types[weight_index],
          lwd = PLOT$line_width
        )
      }

      graphics::axis(
        side = 1,
        at = seq(0.1, 0.9, by = 0.2),
        labels = percent_axis(seq(0.1, 0.9, by = 0.2)),
        cex.axis = PLOT$axis_cex
      )
      if (borrowing_index == 1L) {
        graphics::axis(
          side = 2,
          at = y_breaks,
          las = 1,
          cex.axis = PLOT$axis_cex
        )
      }
      graphics::box()
    }

    graphics::mtext(
      PLOT_LABELS$allocation_x,
      side = 1,
      outer = TRUE,
      line = 1.2,
      cex = PLOT$outer_label_cex
    )
    graphics::mtext(
      PLOT_LABELS$wevsi_y,
      side = 2,
      outer = TRUE,
      line = 0.7,
      cex = PLOT$outer_label_cex
    )

    draw_outer_legend(show_maximum_points = FALSE)
  }

  with_graphics_device(
    file.path(FIGURE_DIR, paste0(output_stem, ".png")),
    width = 14,
    height = 5.4,
    type = "png",
    plotting_function = draw
  )
  with_graphics_device(
    file.path(FIGURE_DIR, paste0(output_stem, ".pdf")),
    width = 14,
    height = 5.4,
    type = "pdf",
    plotting_function = draw
  )
}

plot_wenbs_figure <- function(decision_structure, output_stem) {
  curve_data <- wenbs[
    wenbs$decision_structure == decision_structure,
    ,
    drop = FALSE
  ]
  maximum_data <- optimal[
    optimal$decision_structure == decision_structure,
    ,
    drop = FALSE
  ]

  if (nrow(curve_data) == 0L || nrow(maximum_data) == 0L) {
    stop("Missing wENBS curves or maxima for: ", decision_structure, call. = FALSE)
  }

  y_limits <- range(c(0, curve_data$wENBS), finite = TRUE)
  y_padding <- max(diff(y_limits) * 0.035, 1)
  y_limits <- y_limits + c(-y_padding, y_padding)
  y_breaks <- pretty_qaly_breaks(y_limits)

  draw <- function() {
    old_par <- graphics::par(no.readonly = TRUE)
    on.exit(graphics::par(old_par), add = TRUE)

    graphics::par(
      mfrow = c(length(expected_costs), nrow(BORROWING)),
      mar = c(2.2, 4.2, 2.4, 2.2),
      oma = c(6.6, 2.6, 0.6, 4.0),
      xaxs = "i",
      yaxs = "i"
    )
    # Undo the automatic 0.66 text reduction applied to 3x3 layouts.
    graphics::par(cex = 1)

    for (cost_index in seq_along(expected_costs)) {
      cost_value <- expected_costs[cost_index]

      for (borrowing_index in seq_len(nrow(BORROWING))) {
        borrowing_id <- BORROWING$borrowing_id[borrowing_index]
        panel_data <- curve_data[
          curve_data$borrowing_id == borrowing_id &
            curve_data$cost_increment_A_usd == cost_value,
          ,
          drop = FALSE
        ]
        panel_maxima <- maximum_data[
          maximum_data$borrowing_id == borrowing_id &
            maximum_data$cost_increment_A_usd == cost_value,
          ,
          drop = FALSE
        ]

        graphics::plot(
          NA_real_,
          NA_real_,
          xlim = allocation_x_limits(),
          ylim = y_limits,
          xlab = "",
          ylab = "",
          axes = FALSE,
          main = if (cost_index == 1L) {
            BORROWING$borrowing_facet_label[borrowing_index]
          } else {
            ""
          },
          cex.main = PLOT$panel_title_cex
        )
        graphics::abline(
          h = 0,
          lty = PLOT$zero_line_type,
          col = "grey55"
        )
        graphics::abline(
          v = unname(CASE_STUDY$population_share["A"]),
          lty = PLOT$population_share_line_type,
          col = "grey35"
        )

        for (weight_index in seq_along(RAW_EQUITY_WEIGHT_A)) {
          weight_value <- RAW_EQUITY_WEIGHT_A[weight_index]
          curve <- panel_data[
            panel_data$raw_weight_A == weight_value,
            ,
            drop = FALSE
          ]
          curve <- curve[order(curve$p_A), , drop = FALSE]
          maximum <- panel_maxima[
            panel_maxima$raw_weight_A == weight_value,
            ,
            drop = FALSE
          ]

          if (nrow(curve) != length(ALLOCATION_GRID) || nrow(maximum) != 1L) {
            stop("Incomplete main wENBS figure panel.", call. = FALSE)
          }

          graphics::lines(
            curve$p_A,
            curve$wENBS,
            col = weight_colors[weight_index],
            lty = PLOT$line_types[weight_index],
            lwd = PLOT$line_width
          )

          graphics::points(
            maximum$p_A_optimal,
            maximum$maximum_wENBS,
            pch = PLOT$maximum_point_character,
            cex = PLOT$maximum_point_size,
            col = weight_colors[weight_index]
          )
        }

        if (cost_index == length(expected_costs)) {
          graphics::axis(
            side = 1,
            at = seq(0.1, 0.9, by = 0.2),
            labels = percent_axis(seq(0.1, 0.9, by = 0.2)),
            cex.axis = PLOT$axis_cex
          )
        }
        if (borrowing_index == 1L) {
          graphics::axis(
            side = 2,
            at = y_breaks,
            las = 1,
            cex.axis = PLOT$axis_cex
          )
        }
        graphics::box()

        # Rotated row strip: its width stays one text line regardless of the
        # label, so it cannot collide with the outer axis title beyond it.
        if (borrowing_index == nrow(BORROWING)) {
          graphics::mtext(
            paste0(
              "$",
              format(cost_value, big.mark = ",", scientific = FALSE, trim = TRUE)
            ),
            side = 4,
            line = 1.0,
            las = 0,
            cex = PLOT$strip_label_cex
          )
        }
      }
    }

    graphics::mtext(
      PLOT_LABELS$allocation_x,
      side = 1,
      outer = TRUE,
      line = 1.2,
      cex = PLOT$outer_label_cex
    )
    graphics::mtext(
      PLOT_LABELS$wenbs_y,
      side = 2,
      outer = TRUE,
      line = 0.8,
      cex = PLOT$outer_label_cex
    )
    graphics::mtext(
      PLOT_LABELS$recruitment_cost_row,
      side = 4,
      outer = TRUE,
      line = 2.2,
      cex = PLOT$outer_label_cex
    )

    draw_outer_legend(show_maximum_points = TRUE)
  }

  with_graphics_device(
    file.path(FIGURE_DIR, paste0(output_stem, ".png")),
    width = 15,
    height = 9.8,
    type = "png",
    plotting_function = draw
  )
  with_graphics_device(
    file.path(FIGURE_DIR, paste0(output_stem, ".pdf")),
    width = 15,
    height = 9.8,
    type = "pdf",
    plotting_function = draw
  )
}

plot_wevsi_figure(
  decision_structure = "common",
  output_stem = "figure1_wevsi_common"
)
plot_wevsi_figure(
  decision_structure = "subgroup",
  output_stem = "figure2_wevsi_subgroup"
)
plot_wenbs_figure(
  decision_structure = "common",
  output_stem = "figure3_wenbs_common_9panel"
)
plot_wenbs_figure(
  decision_structure = "subgroup",
  output_stem = "figure4_wenbs_subgroup_9panel"
)

message("Main figures written to: ", FIGURE_DIR)
