# ==============================================================================
# 06_make_appendix_figures.R
# One wENBS figure per appendix evidence profile. Each figure has a common
# population-level decision in the upper row and subgroup-specific decisions in
# the lower row, with one column per borrowing model.
# ==============================================================================

script_directory <- function() {
  arguments <- commandArgs(trailingOnly = FALSE)
  file_argument <- grep("^--file=", arguments, value = TRUE)

  if (length(file_argument) == 1L) {
    # Rscript encodes spaces in --file= as "~+~"; decode before resolving.
    dirname(normalizePath(
      gsub("~+~", " ", sub("^--file=", "", file_argument), fixed = TRUE)
    ))
  } else {
    getwd()
  }
}

ROOT <- script_directory()
source(file.path(ROOT, "00_analysis_parameters.R"), local = TRUE)

ANALYSIS_SIGNATURE <- compute_analysis_signature(ROOT)
RESULT_DIR <- file.path(ROOT, OUTPUT$appendix_results_directory)
FIGURE_DIR <- file.path(ROOT, OUTPUT$appendix_figures_directory)
dir.create(FIGURE_DIR, recursive = TRUE, showWarnings = FALSE)

wenbs_path <- file.path(RESULT_DIR, "appendix_wenbs_summary.csv")
optimal_path <- file.path(RESULT_DIR, "appendix_optimal_allocation_summary.csv")
required_paths <- c(wenbs_path, optimal_path)
missing_paths <- required_paths[!file.exists(required_paths)]

if (length(missing_paths) > 0L) {
  stop(
    "Missing appendix-analysis result files: ",
    paste(missing_paths, collapse = ", "),
    ". Run 05_run_appendix_analysis.R first.",
    call. = FALSE
  )
}

wenbs <- utils::read.csv(
  wenbs_path,
  stringsAsFactors = FALSE,
  check.names = FALSE
)
optimal <- utils::read.csv(
  optimal_path,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

validate_signature <- function(data, label) {
  if (!("analysis_signature" %in% names(data))) {
    stop(label, " lacks analysis_signature.", call. = FALSE)
  }

  signatures <- unique(as.character(data$analysis_signature))
  signatures <- signatures[!is.na(signatures) & nzchar(signatures)]

  if (length(signatures) != 1L || signatures[1] != ANALYSIS_SIGNATURE) {
    stop(
      label,
      " was not generated by the current code. Run 07_run_all.R.",
      call. = FALSE
    )
  }
}

validate_signature(wenbs, "appendix_wenbs_summary.csv")
validate_signature(optimal, "appendix_optimal_allocation_summary.csv")

expected_costs <- sort(as.numeric(APPENDIX_RECRUITMENT_COST_INCREMENT_A_USD))
observed_costs <- sort(unique(as.numeric(wenbs$cost_increment_A_usd)))
if (length(observed_costs) != length(expected_costs) ||
    any(abs(observed_costs - expected_costs) > 1e-12)) {
  stop(
    "Appendix wENBS results do not match the appendix recruitment-cost scenario.",
    call. = FALSE
  )
}

if (!setequal(unique(wenbs$scenario_id), APPENDIX_SCENARIOS$scenario_id)) {
  stop("Appendix scenario identifiers are incomplete or inconsistent.", call. = FALSE)
}

weight_labels <- format(RAW_EQUITY_WEIGHT_A, trim = TRUE, scientific = FALSE)
weight_colors <- PLOT$colors[seq_along(RAW_EQUITY_WEIGHT_A)]

percent_axis <- function(values) {
  paste0(round(100 * values), "%")
}

# Pad the allocation axis slightly so a maximum marker sitting on the first or
# last grid point is drawn whole rather than sliced by the panel border.
allocation_x_limits <- function() {
  range(ALLOCATION_GRID) + c(-1, 1) * 0.6 * SIMULATION$allocation_step
}

open_graphics_device <- function(path, width, height, type) {
  if (type == "png") {
    grDevices::png(
      filename = path,
      width = width,
      height = height,
      units = "in",
      res = PLOT$png_dpi,
      pointsize = PLOT$base_pointsize
    )
  } else if (type == "pdf") {
    grDevices::pdf(
      file = path,
      width = width,
      height = height,
      useDingbats = FALSE,
      pointsize = PLOT$base_pointsize
    )
  } else {
    stop("Unknown graphics type: ", type, call. = FALSE)
  }
}

with_graphics_device <- function(path, width, height, type, plotting_function) {
  open_graphics_device(path, width, height, type)
  on.exit(grDevices::dev.off(), add = TRUE)
  plotting_function()
  invisible(path)
}

# Equity-weight legend in a reserved strip below the panels. Call last.
draw_outer_legend <- function() {
  graphics::par(
    fig = c(0, 1, 0, 1),
    oma = c(0, 0, 0, 0),
    mar = c(0, 0, 0, 0),
    new = TRUE
  )
  graphics::plot(
    0, 0,
    type = "n",
    axes = FALSE,
    xlab = "",
    ylab = "",
    xlim = c(0, 1),
    ylim = c(0, 1)
  )
  graphics::legend(
    x = 0.5,
    y = 0,
    xjust = 0.5,
    yjust = 0,
    legend = weight_labels,
    col = weight_colors,
    lty = PLOT$line_types,
    lwd = PLOT$line_width,
    pch = rep(PLOT$maximum_point_character, length(weight_labels)),
    pt.cex = rep(PLOT$maximum_point_size, length(weight_labels)),
    title = PLOT_LABELS$equity_legend,
    horiz = TRUE,
    bty = "n",
    cex = PLOT$legend_cex
  )
}

plot_appendix_wenbs <- function(scenario_id, output_stem) {
  scenario_information <- APPENDIX_SCENARIOS[
    APPENDIX_SCENARIOS$scenario_id == scenario_id,
    ,
    drop = FALSE
  ]
  if (nrow(scenario_information) != 1L) {
    stop("Unknown appendix scenario: ", scenario_id, call. = FALSE)
  }

  curve_data <- wenbs[wenbs$scenario_id == scenario_id, , drop = FALSE]
  maximum_data <- optimal[optimal$scenario_id == scenario_id, , drop = FALSE]

  if (nrow(curve_data) == 0L || nrow(maximum_data) == 0L) {
    stop("Missing appendix curves or maxima for ", scenario_id, call. = FALSE)
  }

  # One y-axis across both rows, so the two decision structures are directly
  # comparable within a scenario.
  y_limits <- range(c(0, curve_data$wENBS), finite = TRUE)
  y_padding <- max(diff(y_limits) * 0.035, 1)
  y_limits <- y_limits + c(-y_padding, y_padding)
  y_breaks <- pretty(y_limits, n = 5L)

  draw <- function() {
    old_par <- graphics::par(no.readonly = TRUE)
    on.exit(graphics::par(old_par), add = TRUE)

    graphics::par(
      mfrow = c(length(DECISION_STRUCTURES), nrow(BORROWING)),
      mar = c(2.2, 4.2, 2.4, 2.2),
      oma = c(6.6, 2.6, 3.0, 4.0),
      xaxs = "i",
      yaxs = "i"
    )
    # Undo the automatic 0.66 text reduction applied to multi-column layouts.
    graphics::par(cex = 1)

    for (decision_index in seq_along(DECISION_STRUCTURES)) {
      decision_structure <- DECISION_STRUCTURES[decision_index]

      for (borrowing_index in seq_len(nrow(BORROWING))) {
        borrowing_id <- BORROWING$borrowing_id[borrowing_index]
        panel_data <- curve_data[
          curve_data$borrowing_id == borrowing_id &
            curve_data$decision_structure == decision_structure,
          ,
          drop = FALSE
        ]
        panel_maxima <- maximum_data[
          maximum_data$borrowing_id == borrowing_id &
            maximum_data$decision_structure == decision_structure,
          ,
          drop = FALSE
        ]

        graphics::plot(
          NA_real_,
          NA_real_,
          xlim = allocation_x_limits(),
          ylim = y_limits,
          xlab = "",
          ylab = "",
          axes = FALSE,
          main = if (decision_index == 1L) {
            BORROWING$borrowing_facet_label[borrowing_index]
          } else {
            ""
          },
          cex.main = PLOT$panel_title_cex
        )
        graphics::abline(
          h = 0,
          lty = PLOT$zero_line_type,
          col = "grey55"
        )
        graphics::abline(
          v = unname(CASE_STUDY$population_share["A"]),
          lty = PLOT$population_share_line_type,
          col = "grey35"
        )

        for (weight_index in seq_along(RAW_EQUITY_WEIGHT_A)) {
          weight_value <- RAW_EQUITY_WEIGHT_A[weight_index]
          curve <- panel_data[
            panel_data$raw_weight_A == weight_value,
            ,
            drop = FALSE
          ]
          curve <- curve[order(curve$p_A), , drop = FALSE]
          maximum <- panel_maxima[
            panel_maxima$raw_weight_A == weight_value,
            ,
            drop = FALSE
          ]

          if (nrow(curve) != length(ALLOCATION_GRID) || nrow(maximum) != 1L) {
            stop(
              "Incomplete appendix figure panel for ",
              scenario_id, " / ", decision_structure,
              call. = FALSE
            )
          }

          graphics::lines(
            curve$p_A,
            curve$wENBS,
            col = weight_colors[weight_index],
            lty = PLOT$line_types[weight_index],
            lwd = PLOT$line_width
          )
          graphics::points(
            maximum$p_A_optimal,
            maximum$maximum_wENBS,
            pch = PLOT$maximum_point_character,
            cex = PLOT$maximum_point_size,
            col = weight_colors[weight_index]
          )
        }

        if (decision_index == length(DECISION_STRUCTURES)) {
          graphics::axis(
            side = 1,
            at = seq(0.1, 0.9, by = 0.2),
            labels = percent_axis(seq(0.1, 0.9, by = 0.2)),
            cex.axis = PLOT$axis_cex
          )
        }
        if (borrowing_index == 1L) {
          graphics::axis(
            side = 2,
            at = y_breaks,
            las = 1,
            cex.axis = PLOT$axis_cex
          )
        }
        graphics::box()

        # Rotated row strip naming the decision structure for this row.
        if (borrowing_index == nrow(BORROWING)) {
          graphics::mtext(
            DECISION_ROW_LABELS[[decision_structure]],
            side = 4,
            line = 1.0,
            las = 0,
            cex = PLOT$strip_label_cex
          )
        }
      }
    }

    graphics::mtext(
      scenario_information$scenario_label,
      side = 3,
      outer = TRUE,
      line = 0.9,
      cex = PLOT$outer_label_cex,
      font = 2
    )
    graphics::mtext(
      PLOT_LABELS$allocation_x,
      side = 1,
      outer = TRUE,
      line = 1.2,
      cex = PLOT$outer_label_cex
    )
    graphics::mtext(
      PLOT_LABELS$wenbs_y,
      side = 2,
      outer = TRUE,
      line = 0.8,
      cex = PLOT$outer_label_cex
    )
    graphics::mtext(
      PLOT_LABELS$decision_structure_row,
      side = 4,
      outer = TRUE,
      line = 2.2,
      cex = PLOT$outer_label_cex
    )

    draw_outer_legend()
  }

  with_graphics_device(
    file.path(FIGURE_DIR, paste0(output_stem, ".png")),
    width = 15,
    height = 7.8,
    type = "png",
    plotting_function = draw
  )
  with_graphics_device(
    file.path(FIGURE_DIR, paste0(output_stem, ".pdf")),
    width = 15,
    height = 7.8,
    type = "pdf",
    plotting_function = draw
  )
}

for (scenario_index in seq_len(nrow(APPENDIX_SCENARIOS))) {
  scenario_id <- APPENDIX_SCENARIOS$scenario_id[scenario_index]

  plot_appendix_wenbs(
    scenario_id = scenario_id,
    output_stem = paste0("appendix_", scenario_id, "_wenbs")
  )
}

message("Appendix figures written to: ", FIGURE_DIR)
